version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
  hooks:
    - type: mail
      disabled: true
      levels:
        - panic
      options:
        smtp:
          addr: mail.example.com:25
          username: mailuser
          password: password
          insecure: true
        from: sender@example.com
        to:
          - errors@example.com
storage:
    cache:
        blobdescriptor: redis
    s3:
        bucket: deepkeep-docker-registry
        region: us-west-2
    maintenance:
        uploadpurging:
            enabled: false
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    debug:
        addr: localhost:5001
# auth:
#     token:
#       realm: https://deepkeep.auth0.com/oauth/token
#       service: localhost:5000
#       issuer: https://deepkeep.auth0.com
#       rootcertbundle: deepkeep.pem
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
notifications:
    endpoints:
        - name: local-8082
          url: http://www.deepkeep.co/private/api/v1/dockerevents
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: false
